ДЗ разметка
htmlacademy-htmlcss/2176401-sedona-35 pull request #2
Opened 2022-09-30 07:56 UTC by Evalion8

Добрый день!

2022-09-30 19:47 UTC, DoberBober commented on index.html
> +        <div>
Ссылка.

2022-09-30 19:47 UTC, DoberBober commented on index.html
> +        <div>
nav.

2022-09-30 19:47 UTC, DoberBober commented on index.html
> +          <div>
ul. Li-шки нельзя вкладывать никуда, кроме как в ul/ol.

2022-09-30 19:48 UTC, DoberBober commented on index.html
> +              <img src="./img/Search.png" alt="поиск" />
Оберни эту и следующую картинки в ссылки.

2022-09-30 19:48 UTC, DoberBober commented on index.html
> +          <div>
Див удали, кнопку сделай ссылкой.

2022-09-30 19:49 UTC, DoberBober commented on index.html
> +      <img src="./img/index-background.jpeg" alt="логотип_седона" />
Оберни картинку в отдельный див. Этому диву укажешь фоном картинку с горами. Внутри дива будет картинка с текстом (в формате свг).

2022-09-30 19:51 UTC, DoberBober commented on index.html
> +        <div>
Этот блок чуть переделать. Здесь список из пяти пунктов. В первом и четвертом пунктах, кроме текстов, есть и по однйо картинке. Кроме того, в пятом пункте есть ещё один список из трёх пунктов (жилье/еда/сувениры).

2022-09-30 19:52 UTC, DoberBober commented on index.html
> +        <div>
Див удали, кнопку сделай ссылкой.

2022-09-30 19:52 UTC, DoberBober commented on index.html
> +        <h1><b>ПОДПИШИТЕСЬ НА РАССЫЛКУ</b></h1>
h1 желательно иметь только один на странице.

2022-09-30 19:53 UTC, DoberBober commented on index.html
> +        <div class="custom-field">
form. +пропиши  `action="https://echo.htmlacademy.ru"`.

2022-09-30 19:53 UTC, DoberBober commented on index.html
> +          <button>Подписаться</button>
Никогда не оставляй кнопку без типа. Тут `type="submit"`.

2022-09-30 19:53 UTC, DoberBober commented on index.html
> +    <footer class="socials">
Класс footer, скорее.

2022-09-30 19:54 UTC, DoberBober commented on index.html
> +      <button>
Создай список из трёх пунктов. В каждом пункте по соцсети. Кнопки сделай ссылками и пропиши href-ы (слева от макета есть).

2022-09-30 19:54 UTC, DoberBober commented on index.html
> +      <h1>+7 (812) 812-12-12</h1>
Ссылка. птопиши href (`tel:+78128121212`).

2022-09-30 19:55 UTC, DoberBober commented on index.html
> +      <img src="./img/HTML Academy logo.png" alt="html_academy_logo" />
Тоже оберни в ссылку и пропиши href.

2022-09-30 19:56 UTC, DoberBober commented on index.html
> +    </footer>
Подпапки в img удали, они не нужны. У всех названий удали пробелы и заглавные буквы. Выбери один разделитель слов (дефис или нижнее подчёркивание) и используй его везде.

2022-09-30 19:56 UTC, DoberBober requested changes
Есть правки.

2022-10-03 08:31 UTC, Evalion8 commented on index.html
> +    </footer>
Тут не поняла,что именно является подпапкой img? Если удалить начало ссылки -ломается вложение изо,как правильно удалить подпапки?

2022-10-03 19:47 UTC, DoberBober commented on index.html
> +    </footer>
Папки с icon в названии.
![image](https://user-images.githubusercontent.com/18398812/193665556-5deccc83-864d-41ec-9602-46f1a4cf6159.png)

2022-10-04 16:40 UTC, DoberBober commented on index.html
> +<form>
Форму удали. Кнопку сделай ссылкой.

2022-10-04 16:42 UTC, DoberBober commented on index.html
> +        <img src="./img/index-background.svg" alt="#"/>
Сюда выведи свгшку с текстами (Велком седона...).

2022-10-04 16:42 UTC, DoberBober commented on index.html
> +      <section>
Попозже скину в личку комментарий по поводу этого блока.

2022-10-04 16:43 UTC, DoberBober commented on index.html
> +  <form>
Форму удали. Кнопку сделай ссылкой и вставь после  текста "укажите предполагаемые...".

2022-10-04 16:44 UTC, DoberBober commented on index.html
> +          <input type="submit" value="Подписаться" />
Кнопку вставь в форму, после инпута.

2022-10-04 16:44 UTC, DoberBober commented on index.html
> +          <button type="button">
Баттоны убери. Ссылок хватает.

2022-10-04 16:45 UTC, DoberBober requested changes
В названии файлов и папок не должно быть пробелов, спецсимволов и заглавных букв.

По поводу преимуществ напишу в личку, как буду у компа.

2022-10-04 20:54 UTC, DoberBober commented on index.html
> +        <div>
Поздно уже, напишу тут лучше.)
Смотри у тебя есть список (ul, красный), в нём пять пунктов (li-шки, светло-зелёные). В первом и в пятом пунктах есть див, который группирует тексты и картинка (зеленые). Кроме того, в пятом пункте есть вложенный список (зелёный) из трёх элементов (розовые). Остальные элементы - это просто заголовки, параграфы, картинки.
![image](https://user-images.githubusercontent.com/18398812/193925525-05488217-4e65-4910-a031-4b0339ee543b.png)

2022-10-05 19:47 UTC, DoberBober requested changes
Внеси правки описанные выше. Фотки, которые на фоне под шапкой (на обеих страницах) и фотки преимуществ - jpg. Остальное всё - svg. И по поводу пробелов, спецсимволов и прописных букв не забудь.

2022-10-08 12:50 UTC, merged